name: Proto

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: runner / protolint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: yoheimuta/action-protolint@v1
        with:
          github_token: ${{ secrets.github_token }}
          # Change reviewdog reporter if you need [github-pr-check,github-check,github-pr-review].
          reporter: github-pr-review
          # Change reporter level if you need.
          # GitHub Status Check won't become failure with warning.
          level: warning